str="My name is Hardik"
print(str.count('H'))
print(str.endswith('k'))
print(str.endswith('ik'))
print(str.startswith('M'))
print(str.startswith('My'))
print(str.find('is'))
print(str.index('H'))
print(str.isalnum())
print(str.isalpha())
print(str.isdigit())
print(str.islower())
print(str.isupper())
print(str.isspace())
print(str.lower())
print(str.upper())
print(str)
print(len(str))
str.swapcase()
print(str)
str.replace('My name is','I am')
print(str)
print(format("Welcome", "10s"), end = '#')



